#!/usr/local/bin/node

var path = require('path');
var app = require('./app');

if (process.argv.length > 2) {
  app.loadData().then(function(){
    app.dispatchCommand(process.argv.slice(2).join(' '));
  });
} else {
  app.startRepl();
}
