#!/usr/local/bin/node

var path = require('path');
var app = require('./app');

app.loadData().then(function(){
  if (process.argv.length > 2) {
    app.dispatchCommand(process.argv.slice(2).join(' '));
  } else {
    console.log('Welcome to Treasurer tools, you are now in interactive mode.');
    process.stdin.resume();
    process.stdin.setEncoding('utf8');

    process.stdin.on('data', app.dispatchCommand);
  }
});
